### ISSUE TITLE
DEBUG code in cpp file run, even when DEBUG mode is not set

### ISSUE THREAD

**Issue by joelrader** [pkourany/SeeedRFID_IDE#3]
In flashing the new example file, it uploads correctly and run, but soon locks the Spare Core. If I monitor the serial output, it constantly outputs this block of code:
# ifdef DEBUG

```
Serial.println("SeeedRFID:read() function, and the RFID raw data: ");
for (int i = 0; i < _data.dataLen; ++i)
{
    Serial.println();
    Serial.print(_data.raw[i], HEX);
    Serial.print('\t');
}
Serial.println();
```
# endif

Which seems very counter-intuitive, since in the example file #define DEBUG is commented out. This happens whether I have an RFID reader connected or not. If I add delays into the loop, it doesn't seem to make a difference, the SeeedRFID:read() function looks to be stuck in a loop.

![image](https://cloud.githubusercontent.com/assets/41386/8131760/84ee03ac-10ea-11e5-8d06-73c8cc574323.png)

**Comment by joelrader** [comment]
By my reading of the code, when you call "isAvailable()", then read() is also called. But, I wouldn't think that would be the best approach. Wouldn't it be preferable to separate the two, so once "isAvailable()" is passed, then you could call read().

But, once in read, it appears that it's getting stuck in this block due to "while (_rfidIO->available())". I'm not certain, but it appears that in at least my setup that check never fails, and therefore is stuck.

**Comment by pkourany** [comment]
@raiderj, The problem is that DEBUG is "defined" elsewhere.  Remember, this was a port of an Arduino library.  I will change the DEBUG to DEBUGRFID to avoid the issue.

The idea behind isAvailable() is not to see if the UART has availabe but instead it checks if data on the RFID device is read and is valid.  The (_rfidIO->available()) will not loop forever since it will fail the first time (no UART data in the receive buffer).  It is your code or the demo code that keeps calling isAvailable()!

I updated the IDE library with the DEBUG fixes :)

**Comment by joelrader** [comment]
Perfect, thank you!
